config/routes.rb
Rails.application.routes.draw do

  resources :rails_users do
		resources :rails_roles, :only => [:update,:destroy]
	end

  resources :sti_questionnaires
	resources :alter_referral_sheets #	{ collection { get :row } }
	resources :interview_notes
	resources :testing_facilitations
	resources :contact_informations
	resources :eligibility_screenings

	resource :rails_user_session
	resource :password, :only => [:edit,:update]

	resources :other_specifies, :only => [:show,:index]
	resources :users, :only => [:show,:index]
	resources :studies, :only => [:show,:index]
	resources :question_options, :only => [:show,:index]
	resources :questions, :only => [:show,:index]
	resources :notes, :only => [:show,:index]
	resources :matched_alters, :only => [:show,:index]
	resources :legends, :only => [:show,:index]
	resources :interviewers, :only => [:show,:index]
	resources :interviews, :only => [:show,:index]
	resources :graphs, :only => [:show,:index]
	resources :expressions, :only => [:show,:index]
	resources :answer_lists, :only => [:show,:index]
	resources :answers, :only => [:show,:index]
	resources :alters, :only => [:show,:index]
	resources :alter_prompts, :only => [:show,:index]
	resources :alter_lists, :only => [:show,:index]
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :statics, :only => [:index] do
		collection do
			get :reports, :demographic_counts, :alters_per_ego,
				:black_demographic_counts, :latina_demographic_counts, :trans_demographic_counts,
				:leftover_demographic_counts, :sti_counts
			#	puts app.reports_statics_path
			#	=> /statics/reports
		end
	end
	root :to => "statics#index"

	get 'logout' =>  'rails_user_sessions#destroy'
	get 'login' =>   'rails_user_sessions#new'	#, :as => :login

end

app/models/testing_facilitation.rb
class TestingFacilitation < ApplicationRecord
	validates_length_of :notes, maximum: 65500

	def self.attribute_names
		['participant_prefix','participant_suffix'] + super
	end

	def participant_prefix
		participant_id.to_s.split('_')[0]
	end

	def participant_suffix
		participant_id.to_s.split('_')[1]
	end

end

app/controllers/testing_facilitations_controller.rb
class TestingFacilitationsController < ApplicationController
	before_action :set_testing_facilitation, only: [:show, :edit, :update, :destroy]
	skip_before_action :require_user_can_read, only: [:index]
	before_action :require_user_is_admin_if_csv, only: [:index]

	# GET /testing_facilitations
	# GET /testing_facilitations.json
	def index
		@testing_facilitations = TestingFacilitation.order(:participant_id)
	end

	# GET /testing_facilitations/1
	# GET /testing_facilitations/1.json
	def show
	end

	# GET /testing_facilitations/new
	def new
		@testing_facilitation = TestingFacilitation.new(data_entry_name: current_user.login)
	end

	# GET /testing_facilitations/1/edit
	def edit
		@testing_facilitation.data_entry_name += ", #{current_user.login}"
	end

	# POST /testing_facilitations
	# POST /testing_facilitations.json
	def create
		@testing_facilitation = TestingFacilitation.new(testing_facilitation_params)
		@testing_facilitation.data_entry_name = current_user.login

		respond_to do |format|
			if @testing_facilitation.save
				format.html { redirect_to @testing_facilitation, notice: 'Testing facilitation was successfully created.' }
				format.json { render :show, status: :created, location: @testing_facilitation }
			else
				format.html { render :new }
				format.json { render json: @testing_facilitation.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /testing_facilitations/1
	# PATCH/PUT /testing_facilitations/1.json
	def update
		p = testing_facilitation_params
		p[:data_entry_name] = @testing_facilitation.data_entry_name.to_s + ", #{current_user.login}"
		respond_to do |format|
			if @testing_facilitation.update(p)
				format.html { redirect_to @testing_facilitation, notice: 'Testing facilitation was successfully updated.' }
				format.json { render :show, status: :ok, location: @testing_facilitation }
			else
				format.html { render :edit }
				format.json { render json: @testing_facilitation.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /testing_facilitations/1
	# DELETE /testing_facilitations/1.json
	def destroy
		@testing_facilitation.destroy
		respond_to do |format|
			format.html { redirect_to testing_facilitations_url, notice: 'Testing facilitation was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_testing_facilitation
			@testing_facilitation = TestingFacilitation.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def testing_facilitation_params
			params.require(:testing_facilitation).permit(:date_of_visit, :participant_id, :staff_person, :agree_to_use_home_test_kit_at_site, :agree_to_use_home_test_kit_at_site_refusal_reason, :agree_to_take_test_kit_home, :agree_to_take_test_kit_home_refusal_reason, :agree_to_tell_result_of_home_test_kit, :agree_to_tell_result_of_home_test_kit_refusal_reason, :result_of_home_test_kit, :confirmatory_test_referred_location, :confirmatory_test_referred_appointment, :confirmatory_test_referred_location_other, :indeterminate_test_option, :indeterminate_test_result, :indeterminate_test_referred_to, :urine_to_test, :urine_to_test_refusal_reason, :urine_to_test_refusal_reason_other, :notes, :gonorrhea_result, :chlamydia_result
)
		end
end

app/views/testing_facilitations/_form.html.erb
<% e = YAML.load_file('config/answers.yml')['testing_facilitation'].with_indifferent_access %>

<%= form_for(testing_facilitation) do |f| %>
	<% if testing_facilitation.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(testing_facilitation.errors.count, "error") %> prohibited this testing_facilitation from being saved:</h2>

			<ul>
			<% testing_facilitation.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :data_entry_name %>
		<%= f.text_field :data_entry_name, disabled: true %>
	</div>

	<div class="field">
		<%= f.label :date_of_visit %>
		<%= f.text_field :date_of_visit %>
	</div>

	<div class="field">
		<%= f.label :participant_id %>
		<%= f.text_field :participant_id %>
	</div>

	<div class="field">
		<%= f.label :staff_person %>
		<%= f.text_field :staff_person %>
	</div>

	<div class="field">
		<%= f.radio_button_group_with_labels( :agree_to_use_home_test_kit_at_site, e[:agree_to_use_home_test_kit_at_site] ) %>
	</div>

	<div class="field">
		<%= f.label :agree_to_use_home_test_kit_at_site_refusal_reason %>
		<%= f.text_field :agree_to_use_home_test_kit_at_site_refusal_reason %>
	</div>

	<div class="field">
		<%= f.radio_button_group_with_labels( :agree_to_take_test_kit_home, e[:agree_to_take_test_kit_home] ) %>
	</div>

	<div class="field">
		<%= f.label :agree_to_take_test_kit_home_refusal_reason %>
		<%= f.text_field :agree_to_take_test_kit_home_refusal_reason %>
	</div>

	<div class="field">
		<%= f.radio_button_group_with_labels( :agree_to_tell_result_of_home_test_kit, e[:agree_to_tell_result_of_home_test_kit] ) %>
	</div>

	<div class="field">
		<%= f.label :agree_to_tell_result_of_home_test_kit_refusal_reason %>
		<%= f.text_field :agree_to_tell_result_of_home_test_kit_refusal_reason %>
	</div>

	<div class="field">
		<%= f.radio_button_group_with_labels( :result_of_home_test_kit, e[:result_of_home_test_kit] ) %>
	</div>

	<div class="field">
		<%= f.radio_button_group_with_labels( :confirmatory_test_referred_location, e[:confirmatory_test_referred_location] ) %>
	</div>

	<div class="field">
		<%= f.label :confirmatory_test_referred_appointment %>
		<%= f.text_field :confirmatory_test_referred_appointment %>
	</div>

	<div class="field">
		<%= f.label :confirmatory_test_referred_location_other %>
		<%= f.text_field :confirmatory_test_referred_location_other %>
	</div>

	<div class="field">
		<%= f.radio_button_group_with_labels( :indeterminate_test_option, e[:indeterminate_test_option] ) %>
	</div>

	<div class="field">
		<%= f.label :indeterminate_test_result %>
		<%= f.text_field :indeterminate_test_result %>
	</div>

	<div class="field">
		<%= f.label :indeterminate_test_referred_to %>
		<%= f.text_field :indeterminate_test_referred_to %>
	</div>

	<div class="field">
		<%= f.radio_button_group_with_labels( :urine_to_test, e[:urine_to_test] ) %>
	</div>

	<div class="field">
		<%= f.radio_button_group_with_labels( :urine_to_test_refusal_reason, e[:urine_to_test_refusal_reason] ) %>
	</div>

	<div class="field">
		<%= f.label :urine_to_test_refusal_reason_other %>
		<%= f.text_field :urine_to_test_refusal_reason_other %>
	</div>

	<div class="field">
		<%= f.radio_button_group_with_labels( :gonorrhea_result, e[:gonorrhea_result] ) %>
	</div>

	<div class="field">
		<%= f.radio_button_group_with_labels( :chlamydia_result, e[:chlamydia_result] ) %>
	</div>

	<div class="field">
		<%= f.label :notes %>
		<%= f.text_area :notes %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/testing_facilitations/edit.html.erb
<h1>Editing Testing Facilitation</h1>

<%= render 'form', testing_facilitation: @testing_facilitation %>

<% if current_user.present? and current_user.can_read? %>
<%= link_to 'Show', @testing_facilitation %> |
<%= link_to 'Back', testing_facilitations_path %>
<% end %>

app/views/testing_facilitations/index.csv.erb
<% require 'csv' -%>
<%= TestingFacilitation.attribute_names.to_csv -%>
<% @testing_facilitations.each do |testing_facilitation| %>
<%= TestingFacilitation.attribute_names.collect{|a| testing_facilitation.send(a) }.to_csv.html_safe -%>
<% end %>

app/views/testing_facilitations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Testing Facilitations
<% if current_user.present? and current_user.is_admin? %>
[ <%= link_to 'Download CSV', testing_facilitations_path(format:'csv') %> ]
<% end %>
<% if current_user.present? and current_user.can_create? %>
[ <%= link_to 'New Testing Facilitation', new_testing_facilitation_path %> ]
<% end %>
</h1>
<br>

<table class='tablesorter'>
	<thead>
		<tr>
			<th>&nbsp;</th>
			<th>Data entry name</th>
			<th>Participant ID</th>
<% if current_user.present? and current_user.can_read? %>
			<th>Participant prefix</th>
			<th>Participant suffix</th>
			<th>Date of visit</th>
			<th>Staff person</th>
			<th>Agree to use home test kit at site</th>
			<th>Agree to use home test kit at site refusal reason</th>
			<th>Agree to take test kit home</th>
			<th>Agree to take test kit home refusal reason</th>
			<th>Agree to tell result of home test kit</th>
			<th>Agree to tell result of home test kit refusal reason</th>
			<th>Result of home test kit</th>
			<th>Confirmatory test referred location</th>
			<th>Confirmatory test referred appointment</th>
			<th>Confirmatory test referred location other</th>
			<th>Indeterminate test option</th>
			<th>Indeterminate test result</th>
			<th>Indeterminate test referred to</th>
			<th>Urine to test</th>
			<th>Urine to test refusal reason</th>
			<th>Urine to test refusal reason other</th>
			<th>Gonorrhea Result</th>
			<th>Chlamydia Result</th>
			<th>Notes</th>
<% end %>
		</tr>
	</thead>

	<tbody>
		<% @testing_facilitations.each do |testing_facilitation| %>
			<tr>
				<td>
				<% if current_user.present? and current_user.can_read? %>
					<%= link_to 'Show', testing_facilitation %>
				<% end %>
				<% if current_user.present? and current_user.can_update? %>
					<%= link_to 'Edit', edit_testing_facilitation_path(testing_facilitation) %>
				<% end %>
				<% if current_user.present? and current_user.can_destroy? %>
					<%= link_to 'Destroy', testing_facilitation, method: :delete, data: { confirm: 'Are you sure?' } %>
				<% end %>
				</td>
				<td><%= testing_facilitation.data_entry_name %></td>
				<td><%= testing_facilitation.participant_id %></td>
<% if current_user.present? and current_user.can_read? %>
				<td><%= testing_facilitation.participant_prefix %></td>
				<td><%= testing_facilitation.participant_suffix %></td>
				<td><%= testing_facilitation.date_of_visit %></td>
				<td><%= testing_facilitation.staff_person %></td>
				<td><%= testing_facilitation.agree_to_use_home_test_kit_at_site %></td>
				<td><%= testing_facilitation.agree_to_use_home_test_kit_at_site_refusal_reason %></td>
				<td><%= testing_facilitation.agree_to_take_test_kit_home %></td>
				<td><%= testing_facilitation.agree_to_take_test_kit_home_refusal_reason %></td>
				<td><%= testing_facilitation.agree_to_tell_result_of_home_test_kit %></td>
				<td><%= testing_facilitation.agree_to_tell_result_of_home_test_kit_refusal_reason %></td>
				<td><%= testing_facilitation.result_of_home_test_kit %></td>
				<td><%= testing_facilitation.confirmatory_test_referred_location %></td>
				<td><%= testing_facilitation.confirmatory_test_referred_appointment %></td>
				<td><%= testing_facilitation.confirmatory_test_referred_location_other %></td>
				<td><%= testing_facilitation.indeterminate_test_option %></td>
				<td><%= testing_facilitation.indeterminate_test_result %></td>
				<td><%= testing_facilitation.indeterminate_test_referred_to %></td>
				<td><%= testing_facilitation.urine_to_test %></td>
				<td><%= testing_facilitation.urine_to_test_refusal_reason %></td>
				<td><%= testing_facilitation.urine_to_test_refusal_reason_other %></td>
				<td><%= testing_facilitation.gonorrhea_result %></td>
				<td><%= testing_facilitation.chlamydia_result %></td>
				<td><%= testing_facilitation.notes %></td>
<% end %>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/testing_facilitations/new.html.erb
<h1>New Testing Facilitation</h1>

<%= render 'form', testing_facilitation: @testing_facilitation %>

<%= link_to 'Back', testing_facilitations_path %>

app/views/testing_facilitations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong><%= t 'activerecord.attributes.testing_facilitation.data_entry_name' %>:</strong>
	<%= @testing_facilitation.data_entry_name %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.testing_facilitation.date_of_visit' %>:</strong>
	<%= @testing_facilitation.date_of_visit %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.testing_facilitation.participant_id' %>:</strong>
	<%= @testing_facilitation.participant_id %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.testing_facilitation.staff_person' %>:</strong>
	<%= @testing_facilitation.staff_person %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.testing_facilitation.agree_to_use_home_test_kit_at_site' %>:</strong>
	<%= @testing_facilitation.agree_to_use_home_test_kit_at_site %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.testing_facilitation.agree_to_use_home_test_kit_at_site_refusal_reason' %>:</strong>
	<%= @testing_facilitation.agree_to_use_home_test_kit_at_site_refusal_reason %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.testing_facilitation.agree_to_take_test_kit_home' %>:</strong>
	<%= @testing_facilitation.agree_to_take_test_kit_home %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.testing_facilitation.agree_to_take_test_kit_home_refusal_reason' %>:</strong>
	<%= @testing_facilitation.agree_to_take_test_kit_home_refusal_reason %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.testing_facilitation.agree_to_tell_result_of_home_test_kit' %>:</strong>
	<%= @testing_facilitation.agree_to_tell_result_of_home_test_kit %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.testing_facilitation.agree_to_tell_result_of_home_test_kit_refusal_reason' %>:</strong>
	<%= @testing_facilitation.agree_to_tell_result_of_home_test_kit_refusal_reason %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.testing_facilitation.result_of_home_test_kit' %>:</strong>
	<%= @testing_facilitation.result_of_home_test_kit %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.testing_facilitation.confirmatory_test_referred_location' %>:</strong>
	<%= @testing_facilitation.confirmatory_test_referred_location %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.testing_facilitation.confirmatory_test_referred_appointment' %>:</strong>
	<%= @testing_facilitation.confirmatory_test_referred_appointment %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.testing_facilitation.confirmatory_test_referred_location_other' %>:</strong>
	<%= @testing_facilitation.confirmatory_test_referred_location_other %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.testing_facilitation.indeterminate_test_option' %>:</strong>
	<%= @testing_facilitation.indeterminate_test_option %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.testing_facilitation.indeterminate_test_result' %>:</strong>
	<%= @testing_facilitation.indeterminate_test_result %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.testing_facilitation.indeterminate_test_referred_to' %>:</strong>
	<%= @testing_facilitation.indeterminate_test_referred_to %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.testing_facilitation.urine_to_test' %>:</strong>
	<%= @testing_facilitation.urine_to_test %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.testing_facilitation.urine_to_test_refusal_reason' %>:</strong>
	<%= @testing_facilitation.urine_to_test_refusal_reason %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.testing_facilitation.urine_to_test_refusal_reason_other' %>:</strong>
	<%= @testing_facilitation.urine_to_test_refusal_reason_other %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.testing_facilitation.gonorrhea_result' %>:</strong>
	<%= @testing_facilitation.gonorrhea_result %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.testing_facilitation.chlamydia_result' %>:</strong>
	<%= @testing_facilitation.chlamydia_result %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.testing_facilitation.notes' %>:</strong>
	<%= @testing_facilitation.notes %>
</p>

<% if current_user.present? and current_user.can_update? %>
<%= link_to 'Edit', edit_testing_facilitation_path(@testing_facilitation) %> |
<% end %>
<%= link_to 'Back', testing_facilitations_path %>