config/routes.rb
Rails.application.routes.draw do

  resources :rails_users do
		resources :rails_roles, :only => [:update,:destroy]
	end

  resources :sti_questionnaires
	resources :alter_referral_sheets #	{ collection { get :row } }
	resources :interview_notes
	resources :testing_facilitations
	resources :contact_informations
	resources :eligibility_screenings

	resource :rails_user_session
	resource :password, :only => [:edit,:update]

	resources :other_specifies, :only => [:show,:index]
	resources :users, :only => [:show,:index]
	resources :studies, :only => [:show,:index]
	resources :question_options, :only => [:show,:index]
	resources :questions, :only => [:show,:index]
	resources :notes, :only => [:show,:index]
	resources :matched_alters, :only => [:show,:index]
	resources :legends, :only => [:show,:index]
	resources :interviewers, :only => [:show,:index]
	resources :interviews, :only => [:show,:index]
	resources :graphs, :only => [:show,:index]
	resources :expressions, :only => [:show,:index]
	resources :answer_lists, :only => [:show,:index]
	resources :answers, :only => [:show,:index]
	resources :alters, :only => [:show,:index]
	resources :alter_prompts, :only => [:show,:index]
	resources :alter_lists, :only => [:show,:index]
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :statics, :only => [:index] do
		collection do
			get :reports, :demographic_counts, :alters_per_ego,
				:black_demographic_counts, :latina_demographic_counts, :trans_demographic_counts,
				:leftover_demographic_counts, :sti_counts
			#	puts app.reports_statics_path
			#	=> /statics/reports
		end
	end
	root :to => "statics#index"

	get 'logout' =>  'rails_user_sessions#destroy'
	get 'login' =>   'rails_user_sessions#new'	#, :as => :login

end

app/models/alter_referral_sheet.rb
class AlterReferralSheet < ApplicationRecord

	has_many :alter_referrals

	accepts_nested_attributes_for :alter_referrals, allow_destroy: true

end

app/controllers/alter_referral_sheets_controller.rb
class AlterReferralSheetsController < ApplicationController
	before_action :set_alter_referral_sheet, only: [:show, :edit, :update, :destroy]
	skip_before_action :require_user_can_read, only: [:index]

#	def row
#		render partial: 'alter_referral_form', locals: {f: form_for(AlterReferralSheet.new)}
#		render partial: 'alter_referral_form', locals: {
#			f: ActionView::Helpers::FormBuilder.new('alter_referral_sheet', AlterReferralSheet.new,
#				@template,{})
#		}
#	Can't really do "form_for" with ajax.  Need *_tag stuff.
#	end

	# GET /alter_referral_sheets
	# GET /alter_referral_sheets.json
	def index
		@alter_referral_sheets = AlterReferralSheet.all
	end

	# GET /alter_referral_sheets/1
	# GET /alter_referral_sheets/1.json
	def show
	end

	# GET /alter_referral_sheets/new
	def new
		@alter_referral_sheet = AlterReferralSheet.new(data_entry_name: current_user.login)
	end

	# GET /alter_referral_sheets/1/edit
	def edit
		@alter_referral_sheet.data_entry_name += ", #{current_user.login}"
	end

	# POST /alter_referral_sheets
	# POST /alter_referral_sheets.json
	def create
		@alter_referral_sheet = AlterReferralSheet.new(alter_referral_sheet_params)
		@alter_referral_sheet.data_entry_name = current_user.login

		respond_to do |format|
			if @alter_referral_sheet.save
				format.html { redirect_to @alter_referral_sheet, notice: 'Alter referral sheet was successfully created.' }
				format.json { render :show, status: :created, location: @alter_referral_sheet }
			else
				format.html { render :new }
				format.json { render json: @alter_referral_sheet.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /alter_referral_sheets/1
	# PATCH/PUT /alter_referral_sheets/1.json
	def update
		p = alter_referral_sheet_params
		p[:data_entry_name] = @alter_referral_sheet.data_entry_name.to_s + ", #{current_user.login}"
		respond_to do |format|
			if @alter_referral_sheet.update(p)
#			if @alter_referral_sheet.update(alter_referral_sheet_params)
				format.html { redirect_to @alter_referral_sheet, notice: 'Alter referral sheet was successfully updated.' }
				format.json { render :show, status: :ok, location: @alter_referral_sheet }
			else
				format.html { render :edit }
				format.json { render json: @alter_referral_sheet.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /alter_referral_sheets/1
	# DELETE /alter_referral_sheets/1.json
	def destroy
		@alter_referral_sheet.destroy
		respond_to do |format|
			format.html { redirect_to alter_referral_sheets_url, notice: 'Alter referral sheet was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_alter_referral_sheet
			@alter_referral_sheet = AlterReferralSheet.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def alter_referral_sheet_params
			params.require(:alter_referral_sheet).permit(:ego_id,
				:alter_referrals_attributes => [:id, :plan_to_refer, :name_cell,
					:date_of_alter_interview, :alter_id,
					:date_ego_notified, :date_ego_paid, :_destroy ]
			)
		end
end

app/views/alter_referral_sheets/_alter_referral.html.erb
<tr>
	<td><%= alter_referral_counter + 1 %></td>
	<td><%= alter_referral.plan_to_refer %></td>
	<td><%= alter_referral.name_cell %></td>
	<td><%= alter_referral.date_of_alter_interview %></td>
	<td><%= alter_referral.alter_id %></td>
	<td><%= alter_referral.date_ego_notified %></td>
	<td><%= alter_referral.date_ego_paid %></td>
</tr>

app/views/alter_referral_sheets/_alter_referral_form.html.erb
<tr>
	<td><%= (f.options[:child_index]||0) + 1 %></td>
	<td><%= f.check_box :plan_to_refer %></td>
	<td><%= f.text_field :name_cell %></td>
	<td><%= f.text_field :date_of_alter_interview %></td>
	<td><%= f.text_field :alter_id %></td>
	<td><%= f.text_field :date_ego_notified %></td>
	<td><%= f.text_field :date_ego_paid %></td>
	<td><%= f.check_box :_destroy %></td>
</tr>

app/views/alter_referral_sheets/_form.html.erb
<%= form_for(alter_referral_sheet) do |f| %>
	<% if alter_referral_sheet.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(alter_referral_sheet.errors.count, "error") %> prohibited this alter_referral_sheet from being saved:</h2>

			<ul>
			<% alter_referral_sheet.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :data_entry_name %>
		<%= f.text_field :data_entry_name, disabled: true %>
	</div>

	<div class="field">
		<%= f.label :ego_id %>
		<%= f.text_field :ego_id %>
	</div>

<table id='alter_referral_sheet'>
	<thead><tr>
		<th>&nbsp;</th>
		<th><%= t 'activerecord.attributes.alter_referral.plan_to_refer' %></th>
		<th><%= t 'activerecord.attributes.alter_referral.name_cell' %></th>
		<th><%= t 'activerecord.attributes.alter_referral.date_of_alter_interview' %></th>
		<th><%= t 'activerecord.attributes.alter_referral.alter_id' %></th>
		<th><%= t 'activerecord.attributes.alter_referral.date_ego_notified' %></th>
		<th><%= t 'activerecord.attributes.alter_referral.date_ego_paid' %></th>
		<th>Destroy?</th>
	</tr></thead>
	<tbody>
	<%= f.fields_for :alter_referrals do |alter_referral| %>
		<%= render 'alter_referral_form', f: alter_referral %>
	<% end	#f.fields_for :alter_referrals do |alter_referral| %>
	</tbody>
</table>

	<div class="actions">
		<%= f.submit %>
		<button class='add'>Add 5 Referrals</button>
	</div>
<% end %>

app/views/alter_referral_sheets/edit.html.erb
<h1>Editing Alter Referral Sheet</h1>

<%= render 'form', alter_referral_sheet: @alter_referral_sheet %>

<% if current_user.present? and current_user.can_read? %>
<%= link_to 'Show', @alter_referral_sheet %> |
<%= link_to 'Back', alter_referral_sheets_path %>
<% end %>

app/views/alter_referral_sheets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alter Referral Sheets
<% if current_user.present? and current_user.can_create? %>
[ <%= link_to 'New Alter Referral Sheet', new_alter_referral_sheet_path %> ]
<% end %>
</h1>
<br/>

<table class='tablesorter'>
	<thead>
		<tr>
			<th>&nbsp;</th>
			<th>Data Entry Name</th>
			<th><%= t 'activerecord.attributes.alter_referral_sheet.ego_id' %></th>
<% if current_user.present? and current_user.can_read? %>
			<th>Referrals</th>
<% end %>
		</tr>
	</thead>

	<tbody>
		<% @alter_referral_sheets.each do |alter_referral_sheet| %>
			<tr>
				<td>
				<% if current_user.present? and current_user.can_read? %>
					<%= link_to 'Show', alter_referral_sheet %>
				<% end %>
				<% if current_user.present? and current_user.can_update? %>
					<%= link_to 'Edit', edit_alter_referral_sheet_path(alter_referral_sheet) %>
				<% end %>
				<% if current_user.present? and current_user.can_destroy? %>
					<%= link_to 'Destroy', alter_referral_sheet, method: :delete, data: { confirm: 'Are you sure?' } %>
				<% end %>
				</td>
				<td><%= alter_referral_sheet.data_entry_name %></td>
				<td><%= alter_referral_sheet.ego_id %></td>
<% if current_user.present? and current_user.can_read? %>
				<td><%= alter_referral_sheet.alter_referrals_count %></td>
<% end %>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/alter_referral_sheets/new.html.erb
<h1>New Alter Referral Sheet</h1>

<%= render 'form', alter_referral_sheet: @alter_referral_sheet %>

<%= link_to 'Back', alter_referral_sheets_path %>

app/views/alter_referral_sheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong><%= t 'activerecord.attributes.alter_referral_sheet.data_entry_name' %>:</strong>
	<%= @alter_referral_sheet.data_entry_name %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.alter_referral_sheet.ego_id' %>:</strong>
	<%= @alter_referral_sheet.ego_id %>
</p>

<%# if @alter_referral_sheet.alter_referrals_count > 0 %>
<table>
	<thead><tr>
		<th>&nbsp;</th>
		<th><%= t 'activerecord.attributes.alter_referral.plan_to_refer' %></th>
		<th><%= t 'activerecord.attributes.alter_referral.name_cell' %></th>
		<th><%= t 'activerecord.attributes.alter_referral.date_of_alter_interview' %></th>
		<th><%= t 'activerecord.attributes.alter_referral.alter_id' %></th>
		<th><%= t 'activerecord.attributes.alter_referral.date_ego_notified' %></th>
		<th><%= t 'activerecord.attributes.alter_referral.date_ego_paid' %></th>
	</tr></thead>
	<tbody>
	<%= render partial: 'alter_referral', collection: @alter_referral_sheet.alter_referrals %>
	</tbody>
</table>
<%# end %>


<% if current_user.present? and current_user.can_update? %>
<%= link_to 'Edit', edit_alter_referral_sheet_path(@alter_referral_sheet) %> |
<% end %>
<%= link_to 'Back', alter_referral_sheets_path %>