config/routes.rb
Rails.application.routes.draw do

  resources :rails_users do
		resources :rails_roles, :only => [:update,:destroy]
	end

  resources :sti_questionnaires
	resources :alter_referral_sheets #	{ collection { get :row } }
	resources :interview_notes
	resources :testing_facilitations
	resources :contact_informations
	resources :eligibility_screenings

	resource :rails_user_session
	resource :password, :only => [:edit,:update]

	resources :other_specifies, :only => [:show,:index]
	resources :users, :only => [:show,:index]
	resources :studies, :only => [:show,:index]
	resources :question_options, :only => [:show,:index]
	resources :questions, :only => [:show,:index]
	resources :notes, :only => [:show,:index]
	resources :matched_alters, :only => [:show,:index]
	resources :legends, :only => [:show,:index]
	resources :interviewers, :only => [:show,:index]
	resources :interviews, :only => [:show,:index]
	resources :graphs, :only => [:show,:index]
	resources :expressions, :only => [:show,:index]
	resources :answer_lists, :only => [:show,:index]
	resources :answers, :only => [:show,:index]
	resources :alters, :only => [:show,:index]
	resources :alter_prompts, :only => [:show,:index]
	resources :alter_lists, :only => [:show,:index]
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :statics, :only => [:index] do
		collection do
			get :reports, :demographic_counts, :alters_per_ego,
				:black_demographic_counts, :latina_demographic_counts, :trans_demographic_counts,
				:leftover_demographic_counts, :sti_counts
			#	puts app.reports_statics_path
			#	=> /statics/reports
		end
	end
	root :to => "statics#index"

	get 'logout' =>  'rails_user_sessions#destroy'
	get 'login' =>   'rails_user_sessions#new'	#, :as => :login

end

app/models/eligibility_screening.rb
class EligibilityScreening < ApplicationRecord

	scope :eligible_other_than_age, ->{ 
		where( age: 0 )
		.where( gender_at_birth: 1 )
		.where( race: 1 )
		.where( self.arel_table[:tested_hiv].eq(0).or( self.arel_table[:tested_hiv_result].eq(1) ) )
		.where( self.arel_table[:partner_count].eq(1)
			.or( self.arel_table[:injection_drugs].eq(1) )
			.or( self.arel_table[:partner_injection_drugs].eq(1) )
			.or( self.arel_table[:partner_noninjection_drugs].eq(1) )
			.or( self.arel_table[:partner_hiv_positive].eq(1) )
			.or( self.arel_table[:partner_other_partners].eq(1) )
			.or( self.arel_table[:partner_traded_sex].eq(1) )
			.or( self.arel_table[:partner_man_men].eq(1) ) )
		.where( where_live: 1 )
		.where( willing_to_refer: 1 )
	}

end

app/controllers/eligibility_screenings_controller.rb
class EligibilityScreeningsController < ApplicationController
  before_action :set_eligibility_screening, only: [:show, :edit, :update, :destroy]
	before_action :require_user_is_admin_if_csv, only: [:index]

  # GET /eligibility_screenings
  # GET /eligibility_screenings.json
  def index
    @eligibility_screenings = (params[:eligible_other_than_age])? 
			EligibilityScreening.eligible_other_than_age :
			EligibilityScreening.all
  end

  # GET /eligibility_screenings/1
  # GET /eligibility_screenings/1.json
  def show
  end

  # GET /eligibility_screenings/new
  def new
    @eligibility_screening = EligibilityScreening.new(data_entry_name: current_user.login)
  end

  # GET /eligibility_screenings/1/edit
  def edit
		@eligibility_screening.data_entry_name += ", #{current_user.login}"
  end

  # POST /eligibility_screenings
  # POST /eligibility_screenings.json
  def create
    @eligibility_screening = EligibilityScreening.new(eligibility_screening_params)
		@eligibility_screening.data_entry_name = current_user.login

    respond_to do |format|
      if @eligibility_screening.save
        format.html { redirect_to @eligibility_screening, notice: 'Eligibility screening was successfully created.' }
        format.json { render :show, status: :created, location: @eligibility_screening }
      else
        format.html { render :new }
        format.json { render json: @eligibility_screening.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eligibility_screenings/1
  # PATCH/PUT /eligibility_screenings/1.json
  def update
		p = eligibility_screening_params
		p[:data_entry_name] = @eligibility_screening.data_entry_name.to_s + ", #{current_user.login}"
    respond_to do |format|
      if @eligibility_screening.update(p)
        format.html { redirect_to @eligibility_screening, notice: 'Eligibility screening was successfully updated.' }
        format.json { render :show, status: :ok, location: @eligibility_screening }
      else
        format.html { render :edit }
        format.json { render json: @eligibility_screening.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eligibility_screenings/1
  # DELETE /eligibility_screenings/1.json
  def destroy
    @eligibility_screening.destroy
    respond_to do |format|
      format.html { redirect_to eligibility_screenings_url, notice: 'Eligibility screening was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_eligibility_screening
      @eligibility_screening = EligibilityScreening.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def eligibility_screening_params
      params.require(:eligibility_screening).permit(:how_learned, :how_learned_other, :age, :age_other, :sex, :race, :race_other, :children, :seen_pcp, :marital, :tested_hiv, :tested_hiv_result, :partner_count, :injection_drugs, :partner_injection_drugs, :partner_noninjection_drugs, :partner_hiv_positive, :partner_other_partners, :partner_traded_sex, :partner_man_men, :eligible_q_9_16, :where_live, :where_live_other, :willing_to_refer, :matched_to_ego, :eligible, :name_of_screener, :location_of_screening, :date_of_screening, :time_of_screening, :referred_for_interview, :referred_appointment_date, :referred_appointment_time, :reason_for_refusal, :reason_for_refusal_other, :gender, :gender_at_birth)
    end
end

app/views/eligibility_screenings/_form.html.erb
<% e = YAML.load_file('config/answers.yml')['eligibility_screening'].with_indifferent_access %>

<%= form_for(eligibility_screening) do |f| %>
	<% if eligibility_screening.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(eligibility_screening.errors.count, "error") %> prohibited this eligibility_screening from being saved:</h2>

			<ul>
			<% eligibility_screening.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :data_entry_name %>
		<%= f.text_field :data_entry_name, disabled: true %>
	</div>

	<div class="field">
		<%= f.radio_button_group_with_labels( :how_learned, e[:how_learned] ) %>
		<%= f.label :how_learned_other %>
		<%= f.text_field :how_learned_other %>
	</div>

	<div class="field">
		<%= f.radio_button_group_with_labels( :age, e[:age] ) %>
		<%= f.label :age_other %>
		<%= f.text_field :age_other %>
	</div>

	<div class="field">
		<%= f.radio_button_group_with_labels( :gender, e[:gender] ) %>
	</div>

	<div class="field">
		<%= f.radio_button_group_with_labels( :gender_at_birth, e[:gender_at_birth] ) %>
	</div>

	<br/><a>If not black/African/African American or Latina, then ineligible</a><br/>
	<div class="field">
		<%= f.radio_button_group_with_labels( :race, e[:race] ) %>
		<%= f.label :race_other %>
		<%= f.text_field :race_other %>
	</div>

	<br/><a>Does not affect eligibility</a><br/>
	<div class="field">
		<%= f.radio_button_group_with_labels( :children, e[:children] ) %>
	</div>

	<br/><a>Does not affect eligibility</a><br/>
	<div class="field">
		<%= f.radio_button_group_with_labels( :seen_pcp, e[:seen_pcp] ) %>
	</div>

	<br/><a>Does not affect eligibility</a><br/>
	<div class="field">
		<%= f.radio_button_group_with_labels( :marital, [ "Married", "Single", "Divorced", "Separated" ]) %>
	</div>

	<div class="field">
		<%= f.radio_button_group_with_labels( :tested_hiv, e[:tested_hiv] ) %>
	</div>

	<div class="field">
		<%= f.radio_button_group_with_labels( :tested_hiv_result, e[:tested_hiv_result] ) %>
	</div>

	<br/><a>2 or more, then eligible</a><br/>
	<div class="field">
		<%= f.radio_button_group_with_labels( :partner_count, e[:partner_count] ) %>
	</div>

	<div class="field">
		<%= f.radio_button_group_with_labels( :injection_drugs, e[:injection_drugs] ) %>
	</div>

	<div class="field">
		<%= f.radio_button_group_with_labels( :partner_injection_drugs, e[:partner_injection_drugs] ) %>
	</div>

	<div class="field">
		<%= f.radio_button_group_with_labels( :partner_noninjection_drugs, e[:partner_noninjection_drugs] ) %>
	</div>

	<br/><a>If yes or don’t know, then eligible</a><br/>
	<div class="field">
		<%= f.radio_button_group_with_labels( :partner_hiv_positive, e[:partner_hiv_positive] ) %>
	</div>

	<div class="field">
		<%= f.radio_button_group_with_labels( :partner_other_partners, e[:partner_other_partners] ) %>
	</div>

	<div class="field">
		<%= f.radio_button_group_with_labels( :partner_traded_sex, e[:partner_traded_sex] ) %>
	</div>

	<div class="field">
		<%= f.radio_button_group_with_labels( :partner_man_men, e[:partner_man_men] ) %>
	</div>

	<div class="field">
		<%= f.radio_button_group_with_labels( :eligible_q_9_16, e[:eligible_q_9_16] ) %>
	</div>

	<br/><a>Must live in Reno, Sparks, Carson, North Valleys area</a><br/>
	<div class="field">
		<%= f.radio_button_group_with_labels( :where_live, e[:where_live] ) %>
		<%= f.label :where_live_other %>
		<%= f.text_field :where_live_other %>
	</div>

	<br/><a>Must be willing</a><br/>
	<div class="field">
		<%= f.radio_button_group_with_labels( :willing_to_refer, e[:willing_to_refer] ) %>
	</div>

	<div class="field">
		<%= f.radio_button_group_with_labels( :matched_to_ego, e[:matched_to_ego] ) %>
	</div>

	<div class="field">
		<%= f.radio_button_group_with_labels( :eligible, e[:eligible] ) %>
	</div>

	<p>To be completed after the screening interview:</p>

	<div class="field">
		<%= f.label :name_of_screener %>
		<%= f.text_field :name_of_screener %>
	</div>

	<div class="field">
		<%= f.label :location_of_screening %>
		<%= f.text_field :location_of_screening %>
	</div>

	<div class="field">
		<%= f.label :date_of_screening %>
		<%= f.text_field :date_of_screening %>
	</div>

	<div class="field">
		<%= f.label :time_of_screening %>
		<%= f.text_field :time_of_screening %>
	</div>

	<div class="field">
		<%= f.radio_button_group_with_labels( :referred_for_interview, e[:referred_for_interview] ) %>
		<%= f.label :referred_appointment_date %>
		<%= f.text_field :referred_appointment_date %>
		<%= f.label :referred_appointment_time %>
		<%= f.text_field :referred_appointment_time %>
	</div>

	<div class="field">
		<%= f.radio_button_group_with_labels( :reason_for_refusal, e[:reason_for_refusal] ) %>
		<%= f.text_field :reason_for_refusal_other %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/eligibility_screenings/edit.html.erb
<h1>Editing Eligibility Screening</h1>

<%= render 'form', eligibility_screening: @eligibility_screening %>

<% if current_user.present? and current_user.can_read? %>
<%= link_to 'Show', @eligibility_screening %> |
<%= link_to 'Back', eligibility_screenings_path %>
<% end %>

app/views/eligibility_screenings/index.csv.erb
<% require 'csv' -%>
<%= EligibilityScreening.attribute_names.to_csv -%>
<% @eligibility_screenings.each do |eligibility_screening| %>
<%= EligibilityScreening.attribute_names.collect{|a| eligibility_screening[a] }.to_csv.html_safe -%>
<% end %>

app/views/eligibility_screenings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Eligibility Screenings
<% if params[:eligible_other_than_age] %>
( eligible other than age )
<% end %>
<% if current_user.present? and current_user.is_admin? %>
[ <%= link_to 'Download CSV', eligibility_screenings_path(format:'csv') %> ]
<% end %>
<% if current_user.present? and current_user.can_create? %>
[ <%= link_to 'New Eligibility Screening', new_eligibility_screening_path %> ]
<% end %>
</h1>
<br>

<table class='tablesorter'>
	<thead>
		<tr>
			<th>&nbsp;</th>
			<th>Data Entry Name</th>
			<th>How learned</th>
			<th>How learned other</th>
			<th>Age</th>
			<th>Age Other</th>
			<th>Gender</th>
			<th>Gender at birth</th>
			<th>Race</th>
			<th>Race other</th>
			<th>Children</th>
			<th>Seen pcp</th>
			<th>Marital</th>
			<th>Tested hiv</th>
			<th>Tested hiv result</th>
			<th>Partner count</th>
			<th>Injection drugs</th>
			<th>Partner injection drugs</th>
			<th>Partner noninjection drugs</th>
			<th>Partner hiv positive</th>
			<th>Partner other partners</th>
			<th>Partner traded sex</th>
			<th>Partner man men</th>
			<th>Eligible q 8 15</th>
			<th>Where live</th>
			<th>Where live other</th>
			<th>Willing to refer</th>
			<th>Matched to ego</th>
			<th>Eligible</th>
			<th>Name of screener</th>
			<th>Location of screening</th>
			<th>Date of screening</th>
			<th>Time of screening</th>
			<th>Referred for interview</th>
			<th>Referred appointment date</th>
			<th>Referred appointment time</th>
			<th>Reason for refusal</th>
			<th>Reason for refusal other</th>
		</tr>
	</thead>

	<tbody>
		<% @eligibility_screenings.each do |eligibility_screening| %>
			<tr>
				<td><%= link_to 'Show', eligibility_screening %>
				<% if current_user.present? and current_user.can_update? %>
					<%= link_to 'Edit', edit_eligibility_screening_path(eligibility_screening) %>
				<% end %>
				<% if current_user.present? and current_user.can_destroy? %>
					<%= link_to 'Destroy', eligibility_screening, method: :delete, data: { confirm: 'Are you sure?' } %>
				<% end %>
				</td>
				<td><%= eligibility_screening.data_entry_name %></td>
				<td><%= eligibility_screening.how_learned %></td>
				<td><%= eligibility_screening.how_learned_other %></td>
				<td><%= eligibility_screening.age %></td>
				<td><%= eligibility_screening.age_other %></td>
				<td><%= eligibility_screening.gender %></td>
				<td><%= eligibility_screening.gender_at_birth %></td>
				<td><%= eligibility_screening.race %></td>
				<td><%= eligibility_screening.race_other %></td>
				<td><%= eligibility_screening.children %></td>
				<td><%= eligibility_screening.seen_pcp %></td>
				<td><%= eligibility_screening.marital %></td>
				<td><%= eligibility_screening.tested_hiv %></td>
				<td><%= eligibility_screening.tested_hiv_result %></td>
				<td><%= eligibility_screening.partner_count %></td>
				<td><%= eligibility_screening.injection_drugs %></td>
				<td><%= eligibility_screening.partner_injection_drugs %></td>
				<td><%= eligibility_screening.partner_noninjection_drugs %></td>
				<td><%= eligibility_screening.partner_hiv_positive %></td>
				<td><%= eligibility_screening.partner_other_partners %></td>
				<td><%= eligibility_screening.partner_traded_sex %></td>
				<td><%= eligibility_screening.partner_man_men %></td>
				<td><%= eligibility_screening.eligible_q_9_16 %></td>
				<td><%= eligibility_screening.where_live %></td>
				<td><%= eligibility_screening.where_live_other %></td>
				<td><%= eligibility_screening.willing_to_refer %></td>
				<td><%= eligibility_screening.matched_to_ego %></td>
				<td><%= eligibility_screening.eligible %></td>
				<td><%= eligibility_screening.name_of_screener %></td>
				<td><%= eligibility_screening.location_of_screening %></td>
				<td><%= eligibility_screening.date_of_screening %></td>
				<td><%= eligibility_screening.time_of_screening %></td>
				<td><%= eligibility_screening.referred_for_interview %></td>
				<td><%= eligibility_screening.referred_appointment_date %></td>
				<td><%= eligibility_screening.referred_appointment_time %></td>
				<td><%= eligibility_screening.reason_for_refusal %></td>
				<td><%= eligibility_screening.reason_for_refusal_other %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/eligibility_screenings/new.html.erb
<h1>New Eligibility Screening</h1>

<%= render 'form', eligibility_screening: @eligibility_screening %>

<%= link_to 'Back', eligibility_screenings_path %>

app/views/eligibility_screenings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.data_entry_name' %>:</strong>
	<%= @eligibility_screening.data_entry_name %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.how_learned' %>:</strong>
	<%= @eligibility_screening.how_learned %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.how_learned_other' %>:</strong>
	<%= @eligibility_screening.how_learned_other %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.age' %>:</strong>
	<%= @eligibility_screening.age %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.age_other' %>:</strong>
	<%= @eligibility_screening.age_other %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.gender' %>:</strong>
	<%= @eligibility_screening.gender %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.gender_at_birth' %>:</strong>
	<%= @eligibility_screening.gender_at_birth %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.race' %>:</strong>
	<%= @eligibility_screening.race %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.race_other' %>:</strong>
	<%= @eligibility_screening.race_other %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.children' %>:</strong>
	<%= @eligibility_screening.children %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.seen_pcp' %>:</strong>
	<%= @eligibility_screening.seen_pcp %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.marital' %>:</strong>
	<%= @eligibility_screening.marital %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.tested_hiv' %>:</strong>
	<%= @eligibility_screening.tested_hiv %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.tested_hiv_result' %>:</strong>
	<%= @eligibility_screening.tested_hiv_result %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.partner_count' %>:</strong>
	<%= @eligibility_screening.partner_count %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.injection_drugs' %>:</strong>
	<%= @eligibility_screening.injection_drugs %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.partner_injection_drugs' %>:</strong>
	<%= @eligibility_screening.partner_injection_drugs %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.partner_noninjection_drugs' %>:</strong>
	<%= @eligibility_screening.partner_noninjection_drugs %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.partner_hiv_positive' %>:</strong>
	<%= @eligibility_screening.partner_hiv_positive %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.partner_other_partners' %>:</strong>
	<%= @eligibility_screening.partner_other_partners %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.partner_traded_sex' %>:</strong>
	<%= @eligibility_screening.partner_traded_sex %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.partner_man_men' %>:</strong>
	<%= @eligibility_screening.partner_man_men %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.eligible_q_9_16' %>:</strong>
	<%= @eligibility_screening.eligible_q_9_16 %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.where_live' %>:</strong>
	<%= @eligibility_screening.where_live %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.where_live_other' %>:</strong>
	<%= @eligibility_screening.where_live_other %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.willing_to_refer' %>:</strong>
	<%= @eligibility_screening.willing_to_refer %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.matched_to_ego' %>:</strong>
	<%= @eligibility_screening.matched_to_ego %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.eligible' %>:</strong>
	<%= @eligibility_screening.eligible %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.name_of_screener' %>:</strong>
	<%= @eligibility_screening.name_of_screener %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.location_of_screening' %>:</strong>
	<%= @eligibility_screening.location_of_screening %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.date_of_screening' %>:</strong>
	<%= @eligibility_screening.date_of_screening %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.time_of_screening' %>:</strong>
	<%= @eligibility_screening.time_of_screening %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.referred_for_interview' %>:</strong>
	<%= @eligibility_screening.referred_for_interview %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.referred_appointment_date' %>:</strong>
	<%= @eligibility_screening.referred_appointment_date %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.referred_appointment_time' %>:</strong>
	<%= @eligibility_screening.referred_appointment_time %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.reason_for_refusal' %>:</strong>
	<%= @eligibility_screening.reason_for_refusal %>
</p>

<p>
	<strong><%= t 'activerecord.attributes.eligibility_screening.reason_for_refusal_other' %>:</strong>
	<%= @eligibility_screening.reason_for_refusal_other %>
</p>

<% if current_user.present? and current_user.can_update? %>
<%= link_to 'Edit', edit_eligibility_screening_path(@eligibility_screening) %> |
<% end %>
<%= link_to 'Back', eligibility_screenings_path %>