config/routes.rb
Rails.application.routes.draw do

  resources :rails_users do
		resources :rails_roles, :only => [:update,:destroy]
	end

  resources :sti_questionnaires
	resources :alter_referral_sheets #	{ collection { get :row } }
	resources :interview_notes
	resources :testing_facilitations
	resources :contact_informations
	resources :eligibility_screenings

	resource :rails_user_session
	resource :password, :only => [:edit,:update]

	resources :other_specifies, :only => [:show,:index]
	resources :users, :only => [:show,:index]
	resources :studies, :only => [:show,:index]
	resources :question_options, :only => [:show,:index]
	resources :questions, :only => [:show,:index]
	resources :notes, :only => [:show,:index]
	resources :matched_alters, :only => [:show,:index]
	resources :legends, :only => [:show,:index]
	resources :interviewers, :only => [:show,:index]
	resources :interviews, :only => [:show,:index]
	resources :graphs, :only => [:show,:index]
	resources :expressions, :only => [:show,:index]
	resources :answer_lists, :only => [:show,:index]
	resources :answers, :only => [:show,:index]
	resources :alters, :only => [:show,:index]
	resources :alter_prompts, :only => [:show,:index]
	resources :alter_lists, :only => [:show,:index]
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :statics, :only => [:index] do
		collection do
			get :reports, :demographic_counts, :alters_per_ego,
				:black_demographic_counts, :latina_demographic_counts, :trans_demographic_counts,
				:leftover_demographic_counts, :sti_counts
			#	puts app.reports_statics_path
			#	=> /statics/reports
		end
	end
	root :to => "statics#index"

	get 'logout' =>  'rails_user_sessions#destroy'
	get 'login' =>   'rails_user_sessions#new'	#, :as => :login

end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController

	skip_before_action :require_user_can_read

	def demographic_counts
		@studies = Study.all.collect{|s|s.demographics_hash}
	end

	#	try to move this into the model?

	#	NOTE EGO race includes any of African, Caribean, Black (other), Black (or AA)
	def black_demographic_counts
		@studies = []
		Study.all.each do |study|
			s = {}
			s[:id] = study.id
			s[:name] = study.name
			s[:hisplats] = study.hisplats
			s[:genders] = study.genders
			s[:sexes] = study.sexes
			s[:races] = study.races
			s[:demographics] = study.nested_raw_demographics
				.select{|d|
					(d[:race] & ["African", "Afro-Caribbean", "Black or African-American", "Black, other"]).length > 0
				}
				.collect{|d| d[:assoc] }.flatten.singularize
			@studies << s
		end
		render :demographic_counts
	end

	#	NOTE EGO Race NOT IN African, Caribean, Black (other), Black (or AA)
	#	NOTE EGO Race in Latino OR EGO hispanicity == YES
	def latina_demographic_counts
		@studies = []

		Study.all.each do |study|
			s = {}
			s[:id] = study.id
			s[:name] = study.name
			s[:hisplats] = study.hisplats
			s[:genders] = study.genders
			s[:sexes] = study.sexes
			s[:races] = study.races
			s[:demographics] = study.nested_raw_demographics
				.select{|d|
					( (d[:race] & ["African", "Afro-Caribbean",
						"Black or African-American", "Black, other"]).length == 0 ) &&
					( d[:race].include?("Latino or Hispanic (Example: Mexican)" ) ||
						( d[:hisplat] == ["Yes"] )
					)
				}
				.collect{|d| d[:assoc] }.flatten.singularize
			@studies << s
		end
		render :demographic_counts
	end

	#	NOTE EGO Race NOT IN African, Caribean, Black (other), Black (or AA), Latino
	#	NOTE EGO hispanicity NOT YES
	#	NOTE EGO gender = transfemale or sex == Male
	def trans_demographic_counts
		@studies = []
		Study.all.each do |study|
			s = {}
			s[:id] = study.id
			s[:name] = study.name
			s[:hisplats] = study.hisplats
			s[:genders] = study.genders
			s[:sexes] = study.sexes
			s[:races] = study.races
			s[:demographics] = study.nested_raw_demographics
				.select{|d|
					( ( (d[:race] & ["African", "Afro-Caribbean", "Black or African-American",
						"Black, other", "Latino or Hispanic (Example: Mexican)" ]).length == 0 ) &&
						( d[:hisplat] != ["Yes"] ) &&
						( ( d[:gender] == ["Transfemale"] ) ||
							( d[:sex] == ["Male"] ) )
					)
				}
				.collect{|d| d[:assoc] }.flatten.singularize
			@studies << s
		end
		render :demographic_counts
	end

	#	NOTE EGO Race NOT IN African, Caribean, Black (other), Black (or AA), Latino
	#	NOTE EGO hispanicity NOT YES

	#	NOTE *NOT* EGO gender = transfemale or sex == Male

	def leftover_demographic_counts
		@studies = []
		Study.all.each do |study|
			s = {}
			s[:id] = study.id
			s[:name] = study.name
			s[:hisplats] = study.hisplats
			s[:genders] = study.genders
			s[:sexes] = study.sexes
			s[:races] = study.races
			s[:demographics] = study.nested_raw_demographics
				.select{|d|
					( ( (d[:race] & ["African", "Afro-Caribbean", "Black or African-American",
						"Black, other", "Latino or Hispanic (Example: Mexican)" ]).length == 0 ) &&
						( d[:hisplat] != ["Yes"] ) &&
						( d[:gender] != ["Transfemale"] ) &&
						( d[:sex] != ["Male"] )
					)
				}
				.collect{|d| d[:assoc] }.flatten.singularize
			@studies << s
		end
		render :demographic_counts
	end

#	same filters as above
#	testing facilitation and ego web
#	STI COUNTS
#Rows: Study 1 (AA), 2 (Latina), 3 (trans)
#Columns: # agreed to test for hiv, # told results ov HIV, HIV+, # HIV-, # HIV Ind, # tested for chlamydia / gonorrhea, # Gonorrhea+, # Chlamydia+

	def sti_counts
		studies = Study.all.collect{|s|s.nested_raw_demographics}
		@ego_ids = {}
		@tfs = {}
		@ego_ids['AA'] = studies.flatten.select{|d|
			(d[:race] & ["African", "Afro-Caribbean",
				"Black or African-American", "Black, other"]).length > 0
		}.collect{|d| d[:assoc] }.flatten.collect{|d| d[:subject] }.sort
		@tfs['AA'] = TestingFacilitation.where(participant_id: @ego_ids['AA'])
		@ego_ids['Latina'] = studies.flatten.select{|d|
			( (d[:race] & ["African", "Afro-Caribbean",
				"Black or African-American", "Black, other"]).length == 0 ) &&
			( d[:race].include?("Latino or Hispanic (Example: Mexican)" ) ||
				( d[:hisplat] == ["Yes"] )
			)
		}.collect{|d| d[:assoc] }.flatten.collect{|d| d[:subject] }.sort
		@tfs['Latina'] = TestingFacilitation.where(participant_id: @ego_ids['Latina'])
		@ego_ids['Trans'] = studies.flatten.select{|d|
			( ( (d[:race] & ["African", "Afro-Caribbean", "Black or African-American",
				"Black, other", "Latino or Hispanic (Example: Mexican)" ]).length == 0 ) &&
				( d[:hisplat] != ["Yes"] ) &&
				( ( d[:gender] == ["Transfemale"] ) ||
					( d[:sex] == ["Male"] ) )
			)
		}.collect{|d| d[:assoc] }.flatten.collect{|d| d[:subject] }.sort
		@tfs['Trans'] = TestingFacilitation.where(participant_id: @ego_ids['Trans'])
		@ego_ids['Other'] = studies.flatten.select{|d|
			( ( (d[:race] & ["African", "Afro-Caribbean", "Black or African-American",
				"Black, other", "Latino or Hispanic (Example: Mexican)" ]).length == 0 ) &&
				( d[:hisplat] != ["Yes"] ) &&
				( d[:gender] != ["Transfemale"] ) &&
				( d[:sex] != ["Male"] )
			)
		}.collect{|d| d[:assoc] }.flatten.collect{|d| d[:subject] }.sort
		@tfs['Other'] = TestingFacilitation.where(participant_id: @ego_ids['Other'])
	end

	def alters_per_ego
		@studies = Study.all.collect{|s| s.demographics }.flatten
	end

end

app/views/statics/_demographic_counts.html.erb
<h2>Study ID : <%= study[:id] %>, Name: <%= study[:name] %></h2>
<table class='demographics'>
	<thead>
		<tr>
			<th rowspan='3'>Racial Categories</th>
			<th colspan='<%=study[:hisplats].length*study[:genders].length-%>'>
				Ethnic Categories (Hispanic?)</th>
			<th rowspan='3'>Total</th>
		</tr>
		<tr>
			<% study[:hisplats].each do |hisplat| %>
				<th colspan='<%=study[:genders].length-%>'><%=hisplat-%></th>
			<% end	#study[:hisplats].each do |hisplat| %>
		</tr>
		<tr>
			<% study[:hisplats].length.times do %>
				<% study[:genders].each do |gender| %>
				<th><%= gender.gsub("/"," / ") -%></th>
				<% end #study[:genders].each do |gender| %>
			<% end	#study[:hisplats].length.times do %>
		</tr>
	</thead>
	<tbody>
	<% study[:races].each do |race| %>
		<tr>
			<td><%= race %></td>

<%#

		How exactly does this show multi or zero race counts?

%>

			<% d_r = study[:demographics].select{|v|v[:race].length==1 && v[:race][0] == race} %>
			<% study[:hisplats].each do |hisplat| %>

				<% d_r_h = d_r.select{|v| v[:hisplat][0] == hisplat } %>
				<% study[:genders].each do |gender| %>
					<td><%= d_r_h.select{|v| v[:gender][0] == gender }.length -%></td>
				<% end	#study[:genders].each do |gender| %>

			<% end	#study[:hisplats].each do |hisplat| %>

			<td><%= d_r.length %></td>
		</tr>
	<% end %>


<%# 

	Multiple races?

%>


		<tr>
			<td colspan='<%=study[:hisplats].length*study[:genders].length+2-%>'>
				Total Enrollment:&nbsp;&nbsp;<%= study[:demographics].length %>
			</td>
		</tr>
	</tbody>
</table>

app/views/statics/_study.html.erb
<h2>Study ID : <%= study[:id] %></h2>
<table>
	<thead>
		<tr>
			<th rowspan='3'>Racial Categories</th>
			<th colspan='<%=study[:hisplats].length*study[:genders].length-%>'>
				Ethnic Categories (Hispanic?)</th>
			<th rowspan='3'>Total</th>
		</tr>
		<tr>
			<% study[:hisplats].each do |hisplat| %>
				<th colspan='<%=study[:genders].length-%>'><%=hisplat-%></th>
			<% end	#study[:hisplats].each do |hisplat| %>
		</tr>
		<tr>
			<% study[:hisplats].length.times do %>
				<% study[:genders].each do |gender| %>
				<th><%= gender.gsub("/"," / ") -%></th>
				<% end #study[:genders].each do |gender| %>
			<% end	#study[:hisplats].length.times do %>
		</tr>
	</thead>
	<tbody>
	<% study[:races].each do |race| %>
		<tr>
			<td><%= race %></td>

<%#

		How exactly does this show multi or zero race counts?

%>

			<% d_r = study[:demographics].select{|v|v[:race].length==1 && v[:race][0] == race} %>
			<% study[:hisplats].each do |hisplat| %>

				<% d_r_h = d_r.select{|v| v[:hispanic][0] == hisplat } %>
				<% study[:genders].each do |gender| %>
					<td><%= d_r_h.select{|v| v[:gender][0] == gender }.length -%></td>
				<% end	#study[:genders].each do |gender| %>

			<% end	#study[:hisplats].each do |hisplat| %>

			<td><%= d_r.length %></td>
		</tr>
	<% end %>


<%# 

	Multiple races?

%>


		<tr>
			<td colspan='<%=study[:hisplats].length*study[:genders].length+2-%>'>
				Total Enrollment:&nbsp;&nbsp;<%= study[:demographics].length %>
			</td>
		</tr>
	</tbody>
</table>

app/views/statics/alters_per_ego.html.erb
<table>
	<thead>
		<tr>
			<th>Ego ID</th>
			<th>Alter Count</th>
		</tr>
	</thead>
	<tbody>

<% @studies.collect{|s|s[:subject]}.select{|s|s !~ /_/}.sort.each do |ego_id| %>
		<tr>
			<td><%= ego_id %></td>
			<td><%= @studies.collect{|s|s[:subject]}.flatten.select{|s|s=~/^#{ego_id}_/ }.length %></td>
		</tr>
<% end	#	studies %>

	</tbody>
</table>

app/views/statics/counts.html.erb
<h1>Counts for <%= @studies.count -%> <%= 'study'.pluralize(@studies.count) -%>.</h1>


<%
	s = {}
	s[:id] = 'All'
	s[:hisplats] = @studies.collect{|s|s[:hisplats]}.flatten.uniq
	s[:genders] = @studies.collect{|s|s[:genders]}.flatten.uniq
	s[:sexes] = @studies.collect{|s|s[:sexes]}.flatten.uniq
	s[:races] = @studies.collect{|s|s[:races]}.flatten.uniq
	s[:demographics] = @studies.collect{|s|s[:demographics]}.inject([],:+).flatten
%>

<%= render partial: 'study', locals: { study: s } %>

<br/>
<hr/>
<br/>

<%= render partial: 'study', collection: @studies %>

app/views/statics/demographic_counts.html.erb
<h1><%= action_name.humanize %></h1>
<h2>Counts for <%= @studies.count -%> <%= 'study'.pluralize(@studies.count) -%>.</h2>


<%
	s = {}
	s[:id] = 'All'
	s[:hisplats] = @studies.collect{|s|s[:hisplats]}.flatten.uniq
	s[:genders] = @studies.collect{|s|s[:genders]}.flatten.uniq
	s[:sexes] = @studies.collect{|s|s[:sexes]}.flatten.uniq
	s[:races] = @studies.collect{|s|s[:races]}.flatten.uniq
	s[:demographics] = @studies.collect{|s|s[:demographics]}.inject([],:+).flatten
%>

<%= render partial: 'demographic_counts', locals: { study: s } %>

<br/>
<hr/>
<br/>

<%= render partial: 'demographic_counts', collection: @studies, as: :study %>

app/views/statics/index.html.erb
<ul>
<li>Reports ...</li>
<li>&nbsp;</li>
<li><%= link_to 'ALL Demographic Counts', demographic_counts_statics_path %></li>
<li><%= link_to 'Black Demographic Counts', black_demographic_counts_statics_path %></li>
<li><%= link_to 'Latina Demographic Counts', latina_demographic_counts_statics_path %></li>
<li><%= link_to 'Trans Demographic Counts', trans_demographic_counts_statics_path %></li>
<li><%= link_to 'Leftover Demographic Counts', leftover_demographic_counts_statics_path %></li>
<li><%= link_to 'Alters Per Ego', alters_per_ego_statics_path %></li>
<li><%= link_to 'STI Counts', sti_counts_statics_path %></li>

<li>&nbsp;</li>
<li><hr/></li>
<li>&nbsp;</li>
<li>Rails Specific Resources ...</li>
<li>&nbsp;</li>
<li><%= link_to "STI Questionnaires (#{StiQuestionnaire.count})", sti_questionnaires_path %>
	<%= link_to( "(Create new)", new_sti_questionnaire_path ) if current_user.can_create? %></li>
<!--
<li><%#= link_to "Contact Informations (#{ContactInformation.count})", contact_informations_path %></li>
-->
<li><%= link_to "Eligibility Screenings (#{EligibilityScreening.count})", eligibility_screenings_path %>
	<%= link_to( "(Create new)", new_eligibility_screening_path ) if current_user.can_create? %></li>
<li><%= link_to "Eligibility Screenings (eligible_other_than_age: #{EligibilityScreening.eligible_other_than_age.count})", eligibility_screenings_path( eligible_other_than_age: true) %>( Caitlin's query )</li>
<li><%= link_to "Testing Facilitations (#{TestingFacilitation.count})", testing_facilitations_path %>
	<%= link_to( "(Create new)", new_testing_facilitation_path ) if current_user.can_create? %></li>
<li><%= link_to "Interview Notes (#{InterviewNote.count})", interview_notes_path %>
	<%= link_to( "(Create new)", new_interview_note_path ) if current_user.can_create? %></li>
<li><%= link_to "Alter Referral Sheets (#{AlterReferralSheet.count})", alter_referral_sheets_path %>
	<%= link_to( "(Create new)", new_alter_referral_sheet_path ) if current_user.can_create? %></li>

<li>&nbsp;</li>
<li><hr/></li>
<li>&nbsp;</li>
<li>EGO Web Resources ...</li>
<li>&nbsp;</li>
<li><%= link_to "Alters (#{Alter.count})", alters_path %></li>
<li><%= link_to "Alter Lists (#{AlterList.count})", alter_lists_path %></li>
<li><%= link_to "Alter Prompts (#{AlterPrompt.count})", alter_prompts_path %></li>
<li><%= link_to "Answers (#{Answer.count})", answers_path %></li>
<li><%= link_to "Answer Lists (#{AnswerList.count})", answer_lists_path %></li>
<li><%= link_to "Expressions (#{Expression.count})", expressions_path %></li>
<li><%= link_to "Graphs (#{Graph.count})", graphs_path %></li>
<li><%= link_to "Interviews (#{Interview.count})", interviews_path %></li>
<li><%= link_to "Interviewers (#{Interviewer.count})", interviewers_path %></li>
<li><%= link_to "Legends (#{Legend.count})", legends_path %></li>
<li><%= link_to "Matched Alters (#{MatchedAlter.count})", matched_alters_path %></li>
<li><%= link_to "Notes (#{Note.count})", notes_path %></li>
<li><%= link_to "Other Specifies (#{OtherSpecify.count})", other_specifies_path %></li>
<li><%= link_to "Questions (#{Question.count})", questions_path %></li>
<li><%= link_to "Question Options (#{QuestionOption.count})", question_options_path %></li>
<li><%= link_to "Studies (#{Study.count})", studies_path %></li>
<li><%= link_to "Users (#{User.count})", users_path %></li>

</ul>

app/views/statics/reports.html.erb
<h2>Reports</h2>

<ul>
	<li><%= link_to 'ALL Demographic Counts', demographic_counts_statics_path %></li>
	<li><%= link_to 'Black Demographic Counts', black_demographic_counts_statics_path %></li>
	<li><%= link_to 'Latina Demographic Counts', latina_demographic_counts_statics_path %></li>
	<li><%= link_to 'Trans Demographic Counts', trans_demographic_counts_statics_path %></li>
	<li><%= link_to 'Leftover Demographic Counts', leftover_demographic_counts_statics_path %></li>
	<li><%= link_to 'Alters Per Ego', alters_per_ego_statics_path %></li>
	<li><%= link_to 'STI Counts', sti_counts_statics_path %></li>
</ul>

app/views/statics/sti_counts.html.erb
<!--
#	STI COUNTS
#Rows: Study 1 (AA), 2 (Latina), 3 (trans)
#Columns: # agreed to test for hiv, # told results ov HIV, HIV+, # HIV-, # HIV Ind, # tested for chlamydia / gonorrhea, # Gonorrhea+, # Chlamydia+
-->
<table>
	<thead>
		<tr>
			<th>Funding Grant</th>
			<th>Subject IDs</th>
			<th>#</th>
			<th># with TFs</th>
			<th># agreed to HIV test</th>
			<th># agreed to tell HIV test results</th>
			<th># HIV+</th>
			<th># HIV-</th>
			<th># HIV Ind</th>
			<th># tested for chlamydia / gonorrhea</th>
			<th># Gonorrhea+</th>
			<th># Gonorrhea-</th>
			<th># Chlamydia+</th>
			<th># Chlamydia-</th>
		</tr>
	</thead>
	<tbody>
<% @ego_ids.each_pair do |k,v| %>
		<tr><td><%= k %></td>
			<td><%= v.join(', ') %></td>
			<td><%= v.length %></td>
			<td><%= @tfs[k].length %></td>
			<td><%= @tfs[k].select{|tf| tf.agree_to_use_home_test_kit_at_site == 1 }.length %></td>
			<td><%= @tfs[k].select{|tf| tf.agree_to_tell_result_of_home_test_kit == 1 }.length %></td>
			<td><%= @tfs[k].select{|tf| tf.result_of_home_test_kit == 1 }.length %></td>
			<td><%= @tfs[k].select{|tf| tf.result_of_home_test_kit == 0 }.length %></td>
			<td><%= @tfs[k].select{|tf| tf.result_of_home_test_kit == 20 }.length %></td>
			<td><%= @tfs[k].select{|tf| tf.urine_to_test == 1 }.length %></td>
			<td><%= @tfs[k].select{|tf| tf.gonorrhea_result == 1 }.length %></td>
			<td><%= @tfs[k].select{|tf| tf.gonorrhea_result == 0 }.length %></td>
			<td><%= @tfs[k].select{|tf| tf.chlamydia_result == 1 }.length %></td>
			<td><%= @tfs[k].select{|tf| tf.chlamydia_result == 0 }.length %></td>
		</tr>
<% end %>
	</tbody>
</table>